# Generated by Django 4.0 on 2022-03-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_bosfill_examiner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bosfill',
            name='examiner1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bosfill',
            name='examiner2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bosfill',
            name='examiner3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bosfill',
            name='examiner4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bosfill',
            name='examiner5',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bosfill',
            name='examiner6',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bosfill',
            name='examiner7',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bosfill',
            name='examiner8',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bosfill',
            name='examiner9',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
