# Generated by Django 4.0 on 2022-03-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_bosfill_examiner1_bosfill_examiner2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examiner',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
