# Generated by Django 4.0 on 2022-03-19 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_bosfill_id_alter_examiner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bosfill',
            old_name='nameOfrSchlr',
            new_name='nameOfSchlr',
        ),
    ]
