# Generated by Django 4.0 on 2022-03-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_rename_nameofrschlr_bosfill_nameofschlr'),
    ]

    operations = [
        migrations.AddField(
            model_name='bosfill',
            name='coeStatus',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bosfill',
            name='deptStatus',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
