# Generated by Django 4.0 on 2022-03-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_bosfill_coestatus_bosfill_deptstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bosfill',
            name='deptStatus',
            field=models.CharField(default='Pending', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bosfill',
            name='nameOfSprvsr',
            field=models.CharField(default='Pending', max_length=200, null=True),
        ),
    ]
