# Generated by Django 4.0 on 2022-03-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_bosfill_deptstatus_alter_bosfill_nameofsprvsr'),
    ]

    operations = [
        migrations.AddField(
            model_name='bosfill',
            name='vcStatus',
            field=models.CharField(default='Pending', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='examiner',
            name='selected',
            field=models.CharField(default=False, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='bosfill',
            name='coeStatus',
            field=models.CharField(default='Pending', max_length=200, null=True),
        ),
    ]
