# Generated by Django 4.0 on 2022-04-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_bosfill_vcstatus_examiner_selected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='caste',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='approved',
            name='caste',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
