# Generated by Django 4.0 on 2022-04-06 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_examiner_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bosfill',
            name='examiner9',
        ),
    ]
