# Generated by Django 4.0 on 2022-04-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_remove_bosfill_examiner9'),
    ]

    operations = [
        migrations.AddField(
            model_name='bosfill',
            name='examiner9',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
