# Generated by Django 4.0 on 2022-04-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_bosfill_examiner9'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examiner',
            name='selected',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
