# Generated by Django 4.0 on 2022-04-08 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_examiner_selected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bosfill',
            old_name='deptStatus',
            new_name='acoeStatus',
        ),
    ]
