# Generated by Django 4.0 on 2022-04-09 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_rename_acoestatus_bosfill_acoenote1status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bosfill',
            name='s1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bosfill',
            name='s2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bosfill',
            name='s3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bosfill',
            name='nameOfSprvsr',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
