# Generated by Django 4.0 on 2022-04-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_bosfill_s1_bosfill_s2_bosfill_s3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bosfill',
            name='s4',
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bosfill',
            name='s5',
            field=models.TimeField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bosfill',
            name='s3',
            field=models.DateField(max_length=100, null=True),
        ),
    ]
