# Generated by Django 4.0 on 2022-04-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_bosfill_s4_bosfill_s5_alter_bosfill_s3'),
    ]

    operations = [
        migrations.AddField(
            model_name='bosfill',
            name='s6',
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bosfill',
            name='s7',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bosfill',
            name='s8',
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bosfill',
            name='s9',
            field=models.TimeField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bosfill',
            name='s3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bosfill',
            name='s4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bosfill',
            name='s5',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
