# Generated by Django 4.0 on 2022-04-20 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_bosfill_s6_bosfill_s7_bosfill_s8_bosfill_s9_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bosfill',
            name='s1',
        ),
        migrations.RemoveField(
            model_name='bosfill',
            name='s2',
        ),
        migrations.RemoveField(
            model_name='bosfill',
            name='s3',
        ),
    ]
