# Generated by Django 4.0 on 2022-05-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_bosfill_acoenote1reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='bosfill',
            name='f1',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='bosfill',
            name='f2',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='bosfill',
            name='f3',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='bosfill',
            name='f4',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
