# Generated by Django 4.0 on 2022-05-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_bosfill_f1_bosfill_f2_bosfill_f3_bosfill_f4'),
    ]

    operations = [
        migrations.AddField(
            model_name='bosfill',
            name='acoeNote1Date',
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bosfill',
            name='acoeNote2Date',
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bosfill',
            name='acoeNote3Date',
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bosfill',
            name='coeNote1Date',
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bosfill',
            name='coeNote2Date',
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bosfill',
            name='coeNote3Date',
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bosfill',
            name='vcNote1Date',
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bosfill',
            name='vcNote2Date',
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bosfill',
            name='vcNote3Date',
            field=models.DateField(max_length=100, null=True),
        ),
    ]
