# Generated by Django 4.0 on 2022-05-30 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_bosfill_acoenote1date_bosfill_acoenote2date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bosfill',
            old_name='f4',
            new_name='vivavoce',
        ),
    ]
