# Generated by Django 4.0 on 2022-05-31 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_rename_f4_bosfill_vivavoce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bosfill',
            name='vivavoce',
        ),
    ]
