# Generated by Django 4.0 on 2022-05-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_remove_bosfill_vivavoce'),
    ]

    operations = [
        migrations.AddField(
            model_name='bosfill',
            name='f4',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
