# Generated by Django 4.0 on 2022-06-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_officeauthenticates'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeauthenticates',
            name='nextpage',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
