# Generated by Django 4.0 on 2022-06-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_officeauthenticates_nextpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bosfill',
            name='acoeNote1File',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='bosfill',
            name='acoeNote2File',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='bosfill',
            name='acoeNote3File',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='bosfill',
            name='bfile',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='bosfill',
            name='bname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bosfill',
            name='cid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bosfill',
            name='coeNote1File',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='bosfill',
            name='coeNote2File',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='bosfill',
            name='coeNote3File',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bosfill',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bosfill',
            name='vcNote1Date',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bosfill',
            name='vcNote2Date',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bosfill',
            name='vcNote3Date',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
