# Generated by Django 4.0 on 2022-06-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_bosfill_acoenote1file_bosfill_acoenote2file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bosfill',
            name='vcNote1Date',
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bosfill',
            name='vcNote2Date',
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bosfill',
            name='vcNote3Date',
            field=models.DateField(max_length=100, null=True),
        ),
    ]
