# Generated by Django 4.0.5 on 2022-06-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_remove_bosfill_acoenote1file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='prephdac',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='approved',
            name='prephdac',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='myDate',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
