# Generated by Django 4.0.5 on 2022-06-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_applications_prephdac_approved_prephdac_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='prephdac',
        ),
        migrations.RemoveField(
            model_name='approved',
            name='prephdac',
        ),
        migrations.AddField(
            model_name='applications',
            name='yearofadd',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='approved',
            name='yearofadd',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
