# Generated by Django 4.0.2 on 2022-06-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_remove_applications_prephdac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bosfill',
            name='mode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
