# Generated by Django 4.0 on 2022-07-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_bosfill_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='bosfill',
            name='bosuser',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
