# Generated by Django 4.0.2 on 2022-07-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_bosfill_bosuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='prephdmonthandyear',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='approved',
            name='prephdmonthandyear',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
