# Generated by Django 4.0.2 on 2022-07-05 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_applications_plagairismstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applications',
            old_name='plagairismStatus',
            new_name='plagiarismStatus',
        ),
    ]
