# Generated by Django 4.0.3 on 2022-07-14 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_rename_plagairismstatus_applications_plagiarismstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='tsubmit',
        ),
        migrations.RemoveField(
            model_name='approved',
            name='tsubmit',
        ),
    ]
