# Generated by Django 4.0.3 on 2022-07-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_remove_applications_tsubmit_remove_approved_tsubmit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bosfill',
            old_name='vcNote2File',
            new_name='acoesign',
        ),
        migrations.AddField(
            model_name='bosfill',
            name='coesign',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='bosfill',
            name='vcNote1sign',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
