# Generated by Django 4.0.3 on 2022-07-14 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_rename_vcnote2file_bosfill_acoesign_bosfill_coesign_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bosfill',
            old_name='vcNote1sign',
            new_name='vcsign',
        ),
    ]
