# Generated by Django 4.0.3 on 2022-11-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_rename_vcnote1sign_bosfill_vcsign'),
    ]

    operations = [
        migrations.CreateModel(
            name='PvtOfficeAuthenticates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('nextpage', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
