# Generated by Django 4.0.3 on 2022-11-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_pvtofficeauthenticates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
