# Generated by Django 4.0.3 on 2022-11-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0064_alter_applications_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approved',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
